export const CREATE_ADMIN = "CREATE_ADMIN";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";

export const CREATE_TAXI = "CREATE_TAXI";
export const FETCH_TAXIS = "FETCH_TAXIS";
export const FETCH_TAXI = "FETCH_TAXI";
export const UPDATE_TAXI = "UPDATE_TAXI";

export const CREATE_COMPANY = "CREATE_COMPANY";
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
