export const RESET = "RESET";

export const CREATE_ADMIN = "CREATE_ADMIN";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";

export const CREATE_TAXI = "CREATE_TAXI";
export const FETCH_TAXIS = "FETCH_TAXIS";
export const FETCH_TAXI = "FETCH_TAXI";
export const UPDATE_TAXI = "UPDATE_TAXI";

export const CREATE_COMPANY = "CREATE_COMPANY";
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";

export const CREATE_SECTOR = "CREATE_SECTOR";
export const FETCH_SECTORS = "FETCH_SECTORS";
export const FETCH_SECTOR = "FETCH_SECTOR";
export const UPDATE_SECTOR = "UPDATE_SECTOR";

export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const FETCH_VOUCHERS = "FETCH_VOUCHERS";
